######################## default configuration ####################
baseURL = "https://docs.intelops.ai"
title = "Intelops docs"
theme = "godocs-4"
# google analytics
googleAnalytics = "" # example : UA-123-45
# disable language
disableLanguages = ["fr"] # desable language from here. ex: "fr"

# hugo outputs
[outputFormats]
[outputFormats.JSON]
isPlainText = false

[outputs]
home = ["HTML","JSON"]

# render unsafe html
[markup.goldmark.renderer]
unsafe = true

# table of content
[markup.tableOfContents]
startLevel = 0
endLevel = 6
ordered = false

#################### default parameters ################################
[params]
# meta description
author = "Themefisher"
description = "This is meta description"
# contact form action
contact_form_action = "#" # contact form works with https://formspree.io
# feedback form action
feedback_form_action = "#" # contact form works with https://formspree.io
# current doc version [folder_name]
latestDocVersion = "1.2"
# enable/disable Doc Version
docVersion = true
# frequently asked question in homepage
faq = true

# logo
[params.logo]
main = "images/intelops1.png"
favicon = "images/favicon-intelops.png"
main_site_link = "https://intelops.ai/"
site_logo = "images/intelops-gear-only-1.png"
docs_logo = "images/docs-logo.png"

# Preloader
[params.preloader]
enable = false
preloader = "images/loader.png" # use jpg, png, svg or gif format.

# Navigation button
[[params.nav_button]]
style = "solid"   # available style: solid, outline
label = "contact"
link = "contact/"


############################# social site ########################
[[params.social]]
title = "facebook"
icon = "fab fa-facebook" # fontawesome icon : https://fontawesome.com/icons
link = "#"

[[params.social]]
title = "twitter"
icon = "fab fa-twitter" # fontawesome icon : https://fontawesome.com/icons
link = "#"

[[params.social]]
title = "github"
icon = "fab fa-github" # fontawesome icon : https://fontawesome.com/icons
link = "#"

[[params.social]]
title = "linkedin"
icon = "fab fa-linkedin" # fontawesome icon : https://fontawesome.com/icons
link = "#"


################################### English language #####################################
[Languages.en]
languageName = "En"
languageCode = "en-us"
weight = 1
# copyright
copyright = "Intelops, Inc. TX USA"

# banner
[Languages.en.banner]
title = "Documentation for IntelOps's Projects"
subtitle = "Democratizing Cloud-Native"
image = "images/banner.jpg"

# feedback
[Languages.en.feedback]
title = "Did you find this doc useful?"
content = "Your feedback helps us improve our docs."
positive_placeholder = "What did you like about this doc?"
negative_placeholder = "What can we improve in this doc?"

# call to action
[Languages.en.call_to_action]
enable = true
title = "Still Didn't Find Your Answer?"
image = "images/cta-illustration.jpg"
content = "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam <br> nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam"

# call to action button
[Languages.en.call_to_action.button]
enable = "true"
label = "Submit a ticket"
link = "contact/"


############## English navigation ###############
[[Languages.en.menu.footer]]
name = "Contact"
url = "contact/"
weight = 2

[[Languages.en.menu.footer]]
name = "Github"
url = "https://github.com/themefisher/"
weight = 3


################################### French language #####################################
[Languages.fr]
languageName = "Fr"
languageCode = "fr-fr"
weight = 2
# copyright
copyright = "Intelops, Inc. TX USA"

# banner
[Languages.fr.banner]
title = "Thème de documentation par l'équipe Themefisher"
subtitle = "Lorem ipsum dolor amet, consetetur sadiffspscing elitr, diam nonumy invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua At."
image = "images/banner.jpg"

# feedback
[Languages.fr.feedback]
title = "Avez-vous trouvé ce document utile?"
content = "Vos commentaires nous aident à améliorer nos documents."
positive_placeholder = "Qu'avez-vous aimé dans ce document?"
negative_placeholder = "Que pouvons-nous améliorer dans ce document?"

# call to action
[Languages.fr.call_to_action]
enable = true
title = "Vous n'avez toujours pas trouvé votre réponse?"
image = "images/cta-illustration.jpg"
content = "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam <br> nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam"

# call to action button
[Languages.fr.call_to_action.button]
enable = "true"
label = "Soumettre un ticket"
link = "contact/"


############## French navigation ###############
[[Languages.fr.menu.footer]]
name = "Contact"
url = "contact/"
weight = 2

[[Languages.fr.menu.footer]]
name = "Github"
url = "https://github.com/themefisher/"
weight = 3



############################# Plugins ##############################

# CSS Plugin
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/search/auto-complete.css"
[[params.plugins.css]]
link = "plugins/featherlight/featherlight.min.css"


# JS Plugin
[[params.plugins.js]]
link = "plugins/jquery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/js/all.min.js"
attributes = "crossorigin='anonymous' defer='defer' data-search-pseudo-elements"
[[params.plugins.js]]
link = "plugins/masonry/masonry.min.js"
[[params.plugins.js]]
link = "plugins/featherlight/featherlight.min.js"
[[params.plugins.js]]
link = "plugins/clipboard/clipboard.min.js"
[[params.plugins.js]]
link = "plugins/scrollmenu/scrollmenu.min.js"
[[params.plugins.js]]
link = "plugins/search/auto-complete.js"
[[params.plugins.js]]
link = "plugins/search/search.js"
[[params.plugins.js]]
link = "plugins/search/lunr.min.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search-page.js"

# site variables
[params.variables]
# Color Variables
primary_color = "#F16F33"
text_color = "#1c1e21"
text_color_dark = "#222"
text_color_light = "#999"
body_color = "#fff"
border_color = "#E2E2E2"
black = "#000"
white = "#fff"
light = "#FBFBFB"

# Font Variables
primary_font = "Poppins:wght@300;400;500;600"
primary_font_type = "sans-serif"                         # [serif/sans-serif]
secondary_font = ""
secondary_font_type = ""                                 # [serif/sans-serif]
icon_font = "Font Awesome 5 Free"
